version: "3.9"
services: 
    db: 
        container_name: db 
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: chats
        restart: unless-stopped
        
    server: 
        container_name: server
        restart: unless-stopped
        build: .
        ports:  
            - 8080:8080
        depends_on: 
            - db